export default {
  GET_MESSAGE_USER_LIST_REQUEST: "GET_MESSAGE_USER_LIST_REQUEST",
  GET_MESSAGE_USER_LIST_SUCCESS: "GET_MESSAGE_USER_LIST_SUCCESS",
  GET_MESSAGE_USER_LIST_FAILURE: "GET_MESSAGE_USER_LIST_FAILURE",

  GET_SINGLE_USER_MESSAGES_REQUEST: "GET_SINGLE_USER_MESSAGES_REQUEST",
  GET_SINGLE_USER_MESSAGES_SUCCESS: "GET_SINGLE_USER_MESSAGES_SUCCESS",
  GET_SINGLE_USER_MESSAGES_FAILURE: "GET_SINGLE_USER_MESSAGES_FAILURE",
};
