export default {
  GET_MESSAGE_USER_LIST_REQUEST: "GET_MESSAGE_USER_LIST_REQUEST",
  GET_MESSAGE_USER_LIST_SUCCESS: "GET_MESSAGE_USER_LIST_SUCCESS",
  GET_MESSAGE_USER_LIST_FAILURE: "GET_MESSAGE_USER_LIST_FAILURE",
};
