# Generated by Django 2.2.12 on 2020-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailConfirmationToken',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
