# Generated by Django 2.2.14 on 2020-08-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200731_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='is_deletable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=False, max_length=200, unique=True),
        ),
    ]
