# Generated by Django 2.2.14 on 2020-08-03 15:09

from django.db import migrations
from users.models import SYSTEM_ADMINISTRATOR_TYPE, AUTHOR_TYPE, REVIEWER_TYPE


def create_preserved_user_types(apps, schema_editor):
    # Create 'System Administrator', 'Author', 'Reviewer'
    UserType = apps.get_model('users', 'UserType')

    # clear User Types
    user_types_data = UserType.objects.all()
    for user_type_item in user_types_data:
        if user_type_item.name not in {SYSTEM_ADMINISTRATOR_TYPE, AUTHOR_TYPE, REVIEWER_TYPE}:
            user_type_item.delete()

    system_administrator = UserType.objects.filter(name=SYSTEM_ADMINISTRATOR_TYPE).first()
    if system_administrator is None:
        system_administrator = UserType()
    system_administrator.name = SYSTEM_ADMINISTRATOR_TYPE
    system_administrator.create_questions = True
    system_administrator.review_questions = True
    system_administrator.is_deletable = False
    system_administrator.save()

    author = UserType.objects.filter(name=AUTHOR_TYPE).first()
    if author is None:
        author = UserType()
    author.name = AUTHOR_TYPE
    author.create_questions = True
    author.review_questions = False
    author.is_deletable = False
    author.save()

    reviewer = UserType.objects.filter(name=REVIEWER_TYPE).first()
    if reviewer is None:
        reviewer = UserType()
    reviewer.name = REVIEWER_TYPE
    reviewer.create_questions = False
    reviewer.review_questions = True
    reviewer.is_deletable = False
    reviewer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usertype_is_deletable'),
    ]

    operations = [
        migrations.RunPython(create_preserved_user_types),
    ]
