# Generated by Django 2.2.14 on 2020-08-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200803_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(blank=False, max_length=200, unique=True),
        ),
    ]
