# Generated by Django 2.2.22 on 2021-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200803_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('LeadTeacher', 'Lead Teacher')], default='Editor', max_length=20, verbose_name='Role'),
        ),
    ]
