const questionTypes = {
   CREATE_QUESTION_REQUEST: "CREATE_QUESTION_REQUEST",
   CREATE_QUESTION_SUCCESS: "CREATE_QUESTION_SUCCESS",
   CREATE_QUESTION_FAILURE: "CREATE_QUESTION_FAILURE",
   DELETE_QUESTION_REQUEST: "DELETE_QUESTION_REQUEST",
   DELETE_QUESTION_SUCCESS: "DELETE_QUESTION_SUCCESS",
   DELETE_QUESTION_FAILURE: "DELETE_QUESTION_FAILURE",
   EDIT_QUESTION_REQUEST: "EDIT_QUESTION_REQUEST",
   EDIT_QUESTION_SUCCESS: "EDIT_QUESTION_SUCCESS",
   EDIT_QUESTION_FAILURE: "EDIT_QUESTION_FAILURE",
   GET_QUESTION_REQUEST: "GET_QUESTION_REQUEST",
   GET_QUESTION_SUCCESS: "GET_QUESTION_SUCCESS",
   GET_QUESTION_FAILURE: "GET_QUESTION_FAILURE",
   GETUSER_QUESTION_REQUEST: "GETUSER_QUESTION_REQUEST",
   GETUSER_QUESTION_SUCCESS: "GETUSER_QUESTION_SUCCESS",
   GETUSER_QUESTION_FAILURE: "GETUSER_QUESTION_FAILURE",
};

export default questionTypes;
