# Generated by Django 2.2.22 on 2021-05-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='district_id',
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_establishment.SchoolDistrict'),
        ),
    ]
