# Generated by Django 2.2.22 on 2021-05-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0003_class_classroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroll',
            name='class_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_establishment.Class', verbose_name='class'),
        ),
    ]
