# Generated by Django 2.2.22 on 2021-05-11 18:43

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0004_auto_20210511_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtprincipal',
            options={'verbose_name': 'district boss', 'verbose_name_plural': 'district boss'},
        ),
        migrations.AlterModelOptions(
            name='schoolprincipal',
            options={'verbose_name': 'school boss', 'verbose_name_plural': 'school boss'},
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schooldistrict',
            name='nation',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
