# Generated by Django 2.2.22 on 2021-05-11 18:49

from django.db import migrations
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0005_auto_20210511_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nation',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='school',
            name='state_province',
            field=localflavor.us.models.USStateField(blank=True, default='', max_length=2),
        ),
    ]
