# Generated by Django 2.2.22 on 2021-05-11 19:09

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0006_auto_20210511_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldistrict',
            name='state_province',
            field=localflavor.us.models.USStateField(blank=True, default='', max_length=2),
        ),
    ]
