# Generated by Django 2.2.22 on 2021-05-26 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0007_auto_20210511_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('work_email', models.EmailField(max_length=200)),
                ('personal_email', models.EmailField(blank=True, default='', max_length=200)),
                ('work_phone', models.CharField(blank=True, default='', max_length=200)),
                ('personal_phone', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'assist teacher',
                'verbose_name_plural': 'assist teachers',
            },
        ),
        migrations.CreateModel(
            name='LeadTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('work_email', models.EmailField(max_length=200)),
                ('personal_email', models.EmailField(blank=True, default='', max_length=200)),
                ('work_phone', models.CharField(blank=True, default='', max_length=200)),
                ('personal_phone', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'lead teacher',
                'verbose_name_plural': 'lead teachers',
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='districtprincipal',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_establishment.SchoolDistrict'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schooldistrict',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='schoolprincipal',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_establishment.School'),
        ),
        migrations.AlterField(
            model_name='class',
            name='lead_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_classes', to='educational_establishment.LeadTeacher'),
        ),
        migrations.AlterField(
            model_name='districtprincipal',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='districtprincipal',
            name='personal_phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_establishment.SchoolDistrict', verbose_name='Student district'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Student Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent1_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent1_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent1_phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent2_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent2_phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Student Phone'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='assist_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='educational_establishment.AssistTeacher'),
        ),
    ]
