# Generated by Django 2.2.22 on 2021-06-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_establishment', '0017_auto_20210609_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classquiz',
            name='date_given',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent2_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
