# Generated by Django 2.2.12 on 2020-07-27 09:36

from django.db import migrations
from home.models import NON_REGISTERED_EMAIL_PATH, REGISTERED_EMAIL_PATH, TERMS_CONDITION


def create_settings(apps, schema_editor):
    # Create 'Terms and Conditions', 'non-registered-email', 'registered-email'
    Settings = apps.get_model('home', 'Settings')
    terms = Settings()
    terms.path = TERMS_CONDITION
    terms.value = 'Terms and Conditions'
    terms.save()

    non_registered_email = Settings()
    non_registered_email.path = NON_REGISTERED_EMAIL_PATH
    non_registered_email.value = 'info@spiralmath.net'
    non_registered_email.save()

    registered_email = Settings()
    registered_email.path = REGISTERED_EMAIL_PATH
    registered_email.value = 'success@spiralmath.net'
    registered_email.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200727_0936'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]