# Generated by Django 2.2.15 on 2020-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='unread_counter',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
