# Generated by Django 2.2.15 on 2020-09-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.TextField(default='en', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
