# Generated by Django 2.2.15 on 2020-12-08 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_user(apps, schema_editor):
    '''
    Set client user to already created questions
    '''
    User = apps.get_model('users', 'User')
    client_user = User.objects.filter(email='david.robson@spiralmath.net').all()
    Question = apps.get_model('home', 'Question')
    for question in Question.objects.all():
        question.user = client_user[0]
        question.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_auto_20201012_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_user),
    ]

    # david.robson@spiralmath.net
