# Generated by Django 2.2.15 on 2020-12-17 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201208_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dok',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Depth of Knowledge'),
        ),
    ]
