# Generated by Django 2.2.18 on 2021-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201217_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_level',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Grade Level'),
        ),
    ]
