export default {
  FILE_UPLOAD_REQUEST: "FILE_UPLOAD_REQUEST",
  FILE_UPLOAD_SUCCESS: "FILE_UPLOAD_SUCCESS",
  FILE_UPLOAD_FAILURE: "FILE_UPLOAD_FAILURE",

  TERMS_UPLOAD_REQUEST: "TERMS_UPLOAD_REQUEST",
  TERMS_UPLOAD_SUCCESS: "TERMS_UPLOAD_SUCCESS",
  TERMS_UPLOAD_FAILURE: "TERMS_UPLOAD_FAILURE",

  EMAIL_UPLOAD_REQUEST: "EMAIL_UPLOAD_REQUEST",
  EMAIL_UPLOAD_SUCCESS: "EMAIL_UPLOAD_SUCCESS",
  EMAIL_UPLOAD_FAILURE: "EMAIL_UPLOAD_FAILURE",

  GET_SETTINGS_REQUEST: "GET_SETTINGS_REQUEST",
  GET_SETTINGS_FAILURE: "GET_SETTINGS_FAILURE",
  GET_SETTINGS_SUCCESS: "GET_SETTINGS_SUCCESS",
};
