export const alertTypes = {
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  CLEAR: "CLEAR",
};

export const userTypes = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  CREATE_USER_TYPE: "CREATE_USER_TYPE",
  CREATE_USER_TYPE_SUCCESS: "CREATE_USER_TYPE_SUCCESS",
  CREATE_USER_TYPE_FAILURE: "CREATE_USER_TYPE_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  RESET_REQUEST: "USERS_RESET_REQUEST",
  RESET_SUCCESS: "USERS_RESET_SUCCESS",
  RESET_FAILURE: "USERS_RESET_FAILURE",

  CONFIRMATION_REQUEST: "USERS_CONFIRMATION_REQUEST",
  CONFIRMATION_SUCCESS: "USERS_CONFIRMATION_SUCCESS",
  CONFIRMATION_FAILURE: "USERS_CONFIRMATION_FAILURE",

  CONTACT_REQUEST: "USERS_CONTACT_REQUEST",
  CONTACT_SUCCESS: "USERS_CONTACT_SUCCESS",
  CONTACT_FAILURE: "USERS_CONTACT_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",
};
