# Generated by Django 2.2.18 on 2021-02-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizframeworks',
            options={'ordering': ['title'], 'verbose_name': 'quiz', 'verbose_name_plural': 'quiz frameworks'},
        ),
        migrations.AlterModelOptions(
            name='quizquestions',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'quiz question', 'verbose_name_plural': 'quiz questions'},
        ),
        migrations.RemoveField(
            model_name='quizframeworks',
            name='created_by',
        ),
        migrations.AddField(
            model_name='quizframeworks',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='quizframeworks',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='footer',
            field=models.CharField(max_length=200, verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='grade',
            field=models.CharField(choices=[('PK', 'PK'), ('K', 'K'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=3, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='sequence',
            field=models.DecimalField(decimal_places=1, max_digits=1000, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_framework.QuizFrameworks'),
        ),
    ]
