# Generated by Django 2.2.18 on 2021-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_framework', '0002_auto_20210202_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizframeworks',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
