# Generated by Django 2.2.18 on 2021-05-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_framework', '0004_auto_20210202_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizframeworks',
            options={'ordering': ['title', 'sequence', 'order'], 'verbose_name': 'quiz', 'verbose_name_plural': 'quiz frameworks'},
        ),
    ]
