# Generated by Django 2.2.18 on 2021-05-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_framework', '0005_auto_20210507_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizframeworks',
            options={'verbose_name': 'quiz', 'verbose_name_plural': 'quiz frameworks'},
        ),
    ]
