# Generated by Django 2.2.22 on 2021-06-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_framework', '0006_auto_20210507_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizframeworks',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizframeworks',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
