const quizTypes = {
  GETALL_QUIZ_REQUEST: "GETALL_QUIZ_REQUEST",
  GETALL_QUIZ_SUCCESS: "GETALL_QUIZ_SUCCESS",
  GETALL_QUIZ_FAILURE: "GETALL_QUIZ_FAILURE",
  DELETE_QUIZ_REQUEST: "DELETE_QUIZ_REQUEST",
  DELETE_QUIZ_FAILURE: "DELETE_QUIZ_FAILURE",
  DELETE_QUIZ_SUCCESS: "DELETE_QUIZ_SUCCESS",
  EDIT_QUIZ_REQUEST: "EDIT_QUIZ_REQUEST",
  EDIT_QUIZ_FAILURE: "EDIT_QUIZ_FAILURE",
  EDIT_QUIZ_SUCCESS: "EDIT_QUIZ_SUCCESS",
};

export default quizTypes;
